version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - type: bind
         source: ./db_data
         target: /var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin:latest
     links:
       - db:db
     ports:
       - 8090:80

   wordpress:
     depends_on:
       - db
     image: wordpress:php5.6-apache
     build:
       dockerfile: Dockerfile
       context: ./
     ports:
       - "8089:80"
     restart: always
     volumes:
      - type: bind
        source: ./theme_src
        target: /var/www/html/wp-content/themes/rpl
      - type: bind
        source: ./plugins
        target: /var/www/html/wp-content/plugins
      - type: bind
        source: ./uploads
        target: /var/www/html/wp-content/uploads
      - type: bind
        source: ./max_replace_script
        target: /var/www/html/max_replace_script
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
